[package]
name    = "secrets"
version = "0.11.1"
license = "MIT"

authors     = ["Stephen Touset <stephen@touset.org>"]
description = "Protected-access memory for cryptographic secrets"

homepage      = "https://github.com/stouset/secrets"
repository    = "https://github.com/stouset/secrets"
documentation = "https://stouset.github.io/secrets"
readme        = "README.md"

keywords = [ "crypto", "cryptography", "allocator" ]

[dependencies]
clippy = { version = "~0", optional = true }
libc   = '~0.1'

[features]
default = []
